### PR TITLE
Add support for woff2, mp4, and webm

### PR DESCRIPTION
**Pull request by gaearon**
I added support for `woff2`, `mp4`, and `webm`.
The line was getting very long, so I split it into three.

### CODE REVIEW

**Comment by scottcorgan** [comment]
Sweet! I know you're a busy guy, but probably a good idea to update the README with those types as well!

**Comment by gaearon** [comment]
Whoops, sorry. Done.

**Comment by scottcorgan** [comment]
Published as `1.9.0`

**Comment by gaearon** [comment]
Thanks for the quick turnaround.

**Pull request merged**
