### PR TITLE
Add support for serving sourcemaps

### PR DESCRIPTION
**Pull request by kentcdodds**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Sorry about that extra merge... Using the github editor for this. If you want me to clean that up in a single commit, I'm happy to do so.

**Comment by kentcdodds** [comment]
Just had a thought... Is there a reason that this server couldn't just search first for whether a file exists at the specified route, and if one doesn't, then send up the `index.html`? That way you wouldn't have to deal with all the different filetypes.

**Comment by scottcorgan** [comment]
That is a true statement. It would be easier. This was something quick I threw together before I got serious with the Superstatic module.

In fact, I highly recommend that over this one.

**Comment by kentcdodds** [comment]
Awesome, I'll give that a look. Thanks.

**Pull request closed without merging**
