### PR TITLE
Call serveStatic before serving index.html

### PR DESCRIPTION
**Pull request by geelen**
This simplifies the implementation, since you no longer need to maintain a list of file type extensions. Now, if a file is found by `serveStatic`, it'll be served. If not, fall back to `index.html` (or whatever `file` you set).

The advantage here is that if you _do_ have static `html` files in the directory, they'll be served straight up. Which is super handy if you're mixing-and-matching pushstate and static pages, or if you're doing some React prerendering.

I think this is a more expected behaviour, and should make things easier to maintain in the long run (since you don't have to keep adding file extensions to the `connect-modrewrite` list)

### CODE REVIEW

**Comment by scottcorgan** [comment]
That's a great package and a change I want to see made. This package started as just an experiment to get something working years ago and I guess people started using it.

With that said, I'd love to make this change with tests (which are there are none of at the moment). Any way I could get you to add some tests for this kind of change?

Thanks!

**Comment by scottcorgan** [comment]
@geelen I've added the initial tests in master. They're not all there, but there's enough I think to prove that this PR passes. Go ahead and rebase and let me know.

**Comment by geelen** [comment]
@scottcorgan done.

**Comment by scottcorgan** [comment]
Published as `2.0.0`, among other upgrades. Thanks again!

**Pull request merged**
