### PR TITLE
Add param for passing extra rules into modRewrite

### PR DESCRIPTION
**Pull request by t0m**
Hi, I ran into a situation where I needed a login route in addition to the regular index.html route, so I added an option to prepend arbitrary mod rewrite rules.

### CODE REVIEW

**Comment by scottcorgan** [comment]
@t0m awesome. Can you document it in the README file?

**Comment by t0m** [comment]
Sure, I added in a little blurb and an example. Let me know if that works.

Thanks!

**Comment by scottcorgan** [comment]
This is looking really good.

One thing that worries me is that this is starting to dangerously turn into another module I worked on (https://github.com/firebase/superstatic) in which you can configure all sorts of things, including custom file serving for routes (like this).

Would Superstatic better fit your needs?

**Comment by t0m** [comment]
Oh cool, I'll take a look. That looks like a better fit for what I'm trying to do. Feel free to merge or close, I totally understand wanting to keep this module in between http-server and superstatic in terms of complexity/configurability.

Thanks!

**Pull request closed without merging**
